### PR TITLE
JST SH: Add suction cap MPNs and device name prefix

### PR DESCRIPTION
**Pull request by nbes4**
##### SUMMARY

This PR adds:
- MPNs for the BM variants that have a 'suction cap', indicated by an appended 'T' to the non-'suction cap' MPN
- A StringAttribute FEATURES 'Suction Cap' for the new MPNs
- Prefix all devices with 'JST ' (mind the whitespace)

See https://github.com/LibrePCB/librepcb-parts-generator/pull/131 for the corresponding changes in the generator script

##### DATASHEETS / REFERENCES

_none_

##### OPEN QUESTIONS / UNRESOLVED ISSUES

_none_

##### CHECKLIST

- [x] I have read and followed the library conventions¹.
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] For modified elements, I bumped their version number².
- [ ] I already used the new library elements in a design and verified their correctness (optional).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

### CODE REVIEW

**Comment by nbes4** [comment]
I see it's the "non-canonical file" CI issue again, I thought I fixed it. Will push an update

**Comment by ubruhin** [comment]
> I see it's the "non-canonical file" CI issue again, I thought I fixed it but forgot to run the librepcb-cli locally to verify.

Ah, I suspect you are the first person using `librepcb-parts-generator` on Windows where it might generate CRLF line endings :see_no_evil: 

Probably lines like this (in the entity classes):

```python
with open(path.join(dir_path, '.librepcb-dev'), 'w') as f:
```

would need to be changed to this:

```python
with open(path.join(dir_path, '.librepcb-dev'), 'w', newline='\n') as f:
```

to make it working correctly on Windows.

**Review by ubruhin — APPROVED** [review]
Diff looks good, thank you! :tada:

**Comment by nbes4** [comment]
> Ah, I suspect you are the first person using librepcb-parts-generator on Windows where it might generate CRLF line endings 🙈

Yes, your suspicion is correct 😄 But usually git converts the line endings to LF upon commiting since I have `core.autocrlf=true` but it seems `* -text` inside the `.gitattributes` prevents this from happening. Maybe it'd be a good idea to change the `.gitattributes` to always use LF? Or use the code change you proposed with using `newline='\n'`.

Anyway, thanks for review & merge!

**Comment by ubruhin** [comment]
> Maybe it'd be a good idea to change the .gitattributes to always use LF?

No, IMHO it's the responsibility of the tool (in this case `librepcb-parts-generator`) to generate the desired line endings, not the responsibility of Git. LibrePCB's file format clearly states that Unix line endings shall be used, so it's a bug in the generator not following this specification.

**Pull request merged**
