### PR TITLE
Add JST SH pkg and dev

### PR DESCRIPTION
**Pull request by nbes4**
##### SUMMARY

Add JST SH (SM and BM variants) pkg and dev generated by https://github.com/LibrePCB/librepcb-parts-generator/pull/127

##### DATASHEETS / REFERENCES

https://jst.de/file/download/925/sh-connector

##### OPEN QUESTIONS / UNRESOLVED ISSUES

_empty_

##### CHECKLIST

- [x] I have read and followed the library conventions¹.
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [ ] For modified elements, I bumped their version number².
- [ ] I already used the new library elements in a design and verified their correctness (optional).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

### CODE REVIEW

**Comment by nbes4** [comment]
I am not quite sure why the CI fails 🤔 

The following error is reported for all added files:
>  BM04B-SRSS-TB (f80fd5bc-af6f-4fae-94f0-d8fc8e23b044):
    - Non-canonical file: 'dev/f80fd5bc-af6f-4fae-94f0-d8fc8e23b044/.librepcb-dev'
    - Non-canonical file: 'dev/f80fd5bc-af6f-4fae-94f0-d8fc8e23b044/device.lp'

Chasing this down into the (hopefully) right librepcb-cli function, the following code seems to dislike my files:
```cpp
// Check for non-canonical files (strict mode)
  if (strict) {
    qInfo().noquote() << tr("Check '%1' for non-canonical files...")
                             .arg(prettyPath(fs.getPath(), libDir));

    QStringList paths = fs.checkForModifications();  // can throw
    if (!paths.isEmpty()) {
      // sort file paths to increases readability of console output
      std::sort(paths.begin(), paths.end());
      printErrorHeaderOnce();
      foreach (const QString& path, paths) {
        printErr(QString("    - Non-canonical file: '%1'")
                     .arg(prettyPath(fs.getAbsPath(path), libDir)));
      }
      success = false;
    }
  }
```

But I am not sure what it does except for checking the transactional filesystem for modifications... Maybe someone could give me some _pointers_? 😄

**Comment by ubruhin** [comment]
It means the generated files are not formatted the way LibrePCB would format them. Just open one of the new library elements in LibrePCB, save it to disk (without modifications) and then check the diff with Git.

**Comment by nbes4** [comment]
Alright, should be fixed 😄

**Comment by ubruhin** [comment]
Great, thank you! :tada: 

Btw, if you make an update to add the additional MPNs some day: I just saw the device names should be prefixed with "JST " (the library name "JST" does not act as a namespace for the contained devices) so that could be done then as well. But let's ignore that for now...

**Comment by nbes4** [comment]
Awesome, I'll add the MPNs and the "JST " prefix in upcoming PRs

**Pull request merged**
